# Generated by Django 6.0.2 on 2026-02-27 01:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargePoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge_point_id', models.CharField(db_index=True, help_text='Charge Box Identity, e.g. CBI-146b9c8cceca', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name, e.g. Haifa Station #1', max_length=100)),
                ('vendor', models.CharField(blank=True, default='', max_length=50)),
                ('model', models.CharField(blank=True, default='', max_length=50)),
                ('serial_number', models.CharField(blank=True, default='', max_length=50)),
                ('firmware_version', models.CharField(blank=True, default='', max_length=50)),
                ('location', models.CharField(blank=True, default='', help_text='Address or description', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('faulted', 'Faulted')], default='offline', max_length=10)),
                ('max_power_kw', models.DecimalField(decimal_places=2, default=60, max_digits=7)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('last_boot', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_interval', models.IntegerField(default=300, help_text='Heartbeat interval in seconds')),
                ('is_active', models.BooleanField(default=True, help_text='If False, BootNotification returns Rejected')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Charge Point',
                'verbose_name_plural': 'Charge Points',
                'db_table': 'chargers_charge_point',
            },
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_id', models.PositiveSmallIntegerField(help_text='OCPP connector ID. 1-based. 0 = charge point itself.')),
                ('connector_type', models.CharField(blank=True, choices=[('ccs1', 'CCS-1 (DC)'), ('ccs2', 'CCS-2 (DC)'), ('chademo', 'CHAdeMO (DC)'), ('type2', 'Type 2 (AC)'), ('type1', 'Type 1 (AC)')], default='', max_length=10)),
                ('ocpp_status', models.CharField(choices=[('Available', 'Available'), ('Preparing', 'Preparing'), ('Charging', 'Charging'), ('SuspendedEV', 'Suspended EV'), ('SuspendedEVSE', 'Suspended EVSE'), ('Finishing', 'Finishing'), ('Reserved', 'Reserved'), ('Unavailable', 'Unavailable'), ('Faulted', 'Faulted')], default='Available', max_length=15)),
                ('error_code', models.CharField(default='NoError', max_length=30)),
                ('error_info', models.CharField(blank=True, default='', max_length=255)),
                ('max_power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('last_status_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='chargers.chargepoint')),
            ],
            options={
                'db_table': 'chargers_connector',
                'ordering': ['charge_point', 'connector_id'],
                'indexes': [models.Index(fields=['ocpp_status'], name='chargers_co_ocpp_st_6cbc49_idx')],
                'unique_together': {('charge_point', 'connector_id')},
            },
        ),
    ]
