# Generated by Django 6.0.2 on 2026-04-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepoint',
            name='boot_enforce_config',
            field=models.TextField(blank=True, default='', help_text='OCPP configuration keys to enforce on every boot. One KEY=VALUE per line. Example: StopTransactionOnInvalidId=true'),
        ),
    ]
