# Generated by Django 6.0.2 on 2026-02-27 01:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_mode', models.CharField(choices=[('end_of_session', 'End of Session'), ('real_time', 'Real-time (deduct on each MeterValues)')], default='end_of_session', max_length=20)),
                ('minimum_balance_to_start', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Minimum wallet balance required to start a session', max_digits=10)),
                ('auto_stop_balance_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Auto-stop session when balance falls to this amount', max_digits=10)),
                ('allow_negative_balance', models.BooleanField(default=False, help_text='If True, session continues even if balance goes negative')),
                ('currency_code', models.CharField(default='ILS', max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Billing Policy',
                'verbose_name_plural': 'Billing Policies',
                'db_table': 'billing_policy',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g. Standard Rate, Night Rate', max_length=100)),
                ('price_per_kwh', models.DecimalField(decimal_places=4, help_text='Price per kWh in configured currency', max_digits=8)),
                ('is_active', models.BooleanField(default=False)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_tariff',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
