# Generated by Django 6.0.2 on 2026-02-27 01:57

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chargers', '0001_initial'),
        ('customers', '0001_initial'),
        ('rfid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.IntegerField(db_index=True, unique=True)),
                ('id_tag', models.CharField(blank=True, default='', max_length=20)),
                ('charge_point_id_str', models.CharField(blank=True, default='', help_text='Denormalized charge_point_id for fast querying', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('faulted', 'Faulted'), ('invalid', 'Invalid')], default='active', max_length=10)),
                ('meter_start_wh', models.IntegerField(default=0)),
                ('meter_stop_wh', models.IntegerField(blank=True, null=True)),
                ('energy_delivered_wh', models.IntegerField(default=0, help_text='Computed: meter_stop - meter_start (or latest meter value - start)')),
                ('energy_delivered_kwh', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('tariff_per_kwh', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Snapshot of tariff at session start', max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cost_deducted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount already deducted from wallet (for real-time mode)', max_digits=10)),
                ('stop_reason', models.CharField(blank=True, default='', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='chargers.chargepoint')),
                ('connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='chargers.connector')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='customers.customer')),
                ('rfid_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='rfid.rfidcard')),
            ],
            options={
                'db_table': 'sessions_charging_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('measurand', models.CharField(default='Energy.Active.Import.Register', help_text='OCPP measurand name', max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('unit', models.CharField(default='Wh', max_length=10)),
                ('phase', models.CharField(blank=True, default='', max_length=10)),
                ('context', models.CharField(blank=True, default='Sample.Periodic', max_length=30)),
                ('location', models.CharField(blank=True, default='Outlet', max_length=10)),
                ('format', models.CharField(blank=True, default='Raw', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chargers.connector')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_values', to='charging_sessions.chargingsession')),
            ],
            options={
                'db_table': 'sessions_meter_value',
                'ordering': ['session', 'timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='chargingsession',
            index=models.Index(fields=['charge_point_id_str', '-created_at'], name='sessions_ch_charge__b88b19_idx'),
        ),
        migrations.AddIndex(
            model_name='chargingsession',
            index=models.Index(fields=['customer', '-created_at'], name='sessions_ch_custome_80957f_idx'),
        ),
        migrations.AddIndex(
            model_name='chargingsession',
            index=models.Index(fields=['status'], name='sessions_ch_status_1ee6db_idx'),
        ),
        migrations.AddIndex(
            model_name='chargingsession',
            index=models.Index(fields=['id_tag'], name='sessions_ch_id_tag_b4a2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='metervalue',
            index=models.Index(fields=['session', 'measurand', 'timestamp'], name='sessions_me_session_a1364f_idx'),
        ),
    ]
