# Generated by Django 6.0.2 on 2026-03-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingsession',
            name='billing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('billed', 'Billed'), ('failed', 'Failed (needs retry)'), ('n/a', 'Not Applicable')], default='pending', help_text='Tracks whether wallet deduction succeeded', max_length=10),
        ),
    ]
