# Generated by Django 6.0.2 on 2026-02-27 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tag', models.CharField(db_index=True, help_text='RFID card UID as reported by charger (OCPP idTag)', max_length=20, unique=True)),
                ('card_number', models.CharField(help_text='Human-readable card number printed on the card', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('lost', 'Lost'), ('expired', 'Expired'), ('unassigned', 'Unassigned')], default='unassigned', max_length=12)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_cards', to='customers.customer')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RFID Card',
                'verbose_name_plural': 'RFID Cards',
                'db_table': 'rfid_card',
                'indexes': [models.Index(fields=['status'], name='rfid_card_status_44b9a0_idx'), models.Index(fields=['customer'], name='rfid_card_custome_f116f3_idx')],
            },
        ),
    ]
