# Generated by Django 6.0.2 on 2026-03-28 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDTapLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tag', models.CharField(db_index=True, max_length=20)),
                ('charge_point_id', models.CharField(blank=True, default='', max_length=100)),
                ('result', models.CharField(choices=[('Accepted', 'Accepted'), ('Blocked', 'Blocked'), ('Expired', 'Expired'), ('Invalid', 'Invalid'), ('ConcurrentTx', 'Concurrent Transaction')], max_length=20)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('tapped_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rfid_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tap_logs', to='rfid.rfidcard')),
            ],
            options={
                'verbose_name': 'RFID Tap Log',
                'verbose_name_plural': 'RFID Tap Logs',
                'db_table': 'rfid_tap_log',
                'ordering': ['-tapped_at'],
            },
        ),
    ]
