# Generated by Django 6.0.2 on 2026-04-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'accounts_page_permission',
                'ordering': ['section', 'display_name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='page_permissions',
            field=models.ManyToManyField(blank=True, help_text='Pages this staff user can access. Admins have access to everything.', related_name='users', to='accounts.pagepermission'),
        ),
    ]
