# Generated by Django 6.0.2 on 2026-04-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vehicle_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('truck', 'Truck'), ('van', 'Van'), ('motorcycle', 'Motorcycle'), ('bus', 'Bus'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='vehicle_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
