# Generated by Django 6.0.2 on 2026-02-27 01:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCPPMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge_point_id', models.CharField(db_index=True, max_length=50)),
                ('direction', models.CharField(choices=[('incoming', 'Incoming (CP -> Server)'), ('outgoing', 'Outgoing (Server -> CP)')], max_length=10)),
                ('message_type', models.IntegerField(choices=[(2, 'Call'), (3, 'CallResult'), (4, 'CallError')])),
                ('unique_id', models.CharField(help_text='OCPP message unique ID', max_length=36)),
                ('action', models.CharField(blank=True, default='', max_length=36)),
                ('payload', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=50)),
                ('error_description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ocpp_message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['charge_point_id', '-created_at'], name='ocpp_messag_charge__f1b640_idx'), models.Index(fields=['action', '-created_at'], name='ocpp_messag_action_cbd153_idx')],
            },
        ),
    ]
